name: thesis_manage_project
description: "Ứng dụng quản lý đề tài đồ án/khóa luận"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  provider: ^6.1.5
  
  # Network & API
  http: ^1.4.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.5.3
  
  # UI components
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  
  # Form validation
  formz: ^0.6.1
  
  # Utilities
  uuid: ^4.2.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
